# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: swift

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/UnlockCodeViewController.xcworkspace -scheme UnlockCodeViewController-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE,OS=12.1' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

# Upload test coverage results to CodeCov
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'UnlockCodeViewController'